elevenlabs:
  api_key: ${ELEVENLABS_API_KEY}
  voice_id: ${ELEVENLABS_VOICE_ID}
  model: eleven_monolingual_v1

whisper:
  api_key: ${WHISPER_API_KEY}
  api_url: https://api.openai.com/v1/audio/transcriptions
  model: whisper-1
  language: en

llm:
  system_prompt: "You are a helpful Horizon Road Rescue dispatcher. Ask for the vehicle type, location, and issue. Confirm if they need immediate towing."

telephony:
  input_format: wav
